name: TypeScript Lint
on:
  pull_request:
  push:
    branches: [master, workflows]

jobs:
  linter-action:
    runs-on: ubuntu-latest
    name: Linter action
    steps:
      - uses: actions/checkout@v2
      - name: Prepare
        run: npm ci
      - name: Linter action
        id: linter
        uses: AntonKornus/TypeScript-Linter@1.0.0
        with:
          folder: src
